=== JSBSim-Team/jsbsim/JSBSimScript.xsd
<?xml version="1.0"?>
<!--<?xml-stylesheet type="text/xsl" href="XMLToDoc.xsl"?>-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation><xs:documentation>
    This schema specifies the format that a JSBSim (www.jsbsim.org) script must
    take to be valid. The JSBSim scripting language provides for specification
    of which aircraft and initialization file will be used for a "batch" run, as
    well as how long it will run, and at what time-step size it will be
    integrated at. Also, "Events" may be defined that can direct the simulation
    to set parameter values when specific conditions have been reached. The
    script author may also specify that some notifications should take place
    when an event is reached.
  </xs:documentation></xs:annotation>

  <xs:include schemaLocation="JSBSimCommon.xsd"/>

  <xs:element name="runscript">
    <xs:annotation><xs:documentation>
      The "runscript" element is the top-level containing XML element. It may
      have a name attribute, that describes briefly what the script does.
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
        <xs:element name="use" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="aircraft" type="xs:token" use="required"/>
            <xs:attribute name="initialize" type="xs:token" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element ref="run" maxOccurs="1"/>
        <xs:element name="output" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="rates" type="ON-OFF" minOccurs="0"/>
              <xs:element name="velocities" type="ON-OFF" minOccurs="0"/>
              <xs:element name="position" type="ON-OFF" minOccurs="0"/>
              <xs:element name="atmosphere" type="ON-OFF" minOccurs="0"/>
              <xs:element name="fcs" type="ON-OFF" minOccurs="0"/>
              <xs:element name="ground_reactions" type="ON-OFF" minOccurs="0"/>
              <xs:element name="propulsion" type="ON-OFF" minOccurs="0"/>
              <xs:element name="simulation" type="ON-OFF" minOccurs="0"/>
              <xs:element name="massprops" type="ON-OFF" minOccurs="0"/>
              <xs:element name="forces" type="ON-OFF" minOccurs="0"/>
              <xs:element name="moments" type="ON-OFF" minOccurs="0"/>
              <xs:element name="aerosurfaces" type="ON-OFF" minOccurs="0"/>
              <xs:element name="coefficients" type="ON-OFF" minOccurs="0"/>
              <xs:element name="property" type="property-with-caption" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:token" use="required"/>
            <xs:attribute name="type" use="required">
              <xs:annotation><xs:documentation>
                The format in which the data output will be issued.
              </xs:documentation></xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:token">
                  <xs:enumeration value="CSV"/>
                  <xs:enumeration value="TABULAR"/>
                  <xs:enumeration value="SOCKET"/>
                  <xs:enumeration value="FLIGHTGEAR"/>
                  <xs:enumeration value="TERMINAL"/>
                  <xs:enumeration value="NONE"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="rate" type="xs:decimal" use="required"/>
            <xs:attribute name="file" type="xs:token" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:token" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="property-with-caption">
    <xs:simpleContent>
      <xs:extension base="property">
        <xs:attribute name="caption" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:element name="run">
    <xs:annotation><xs:documentation>
      The "run" element has as its parent the "runscript" element. The run
      element contains any and all "event" elements. Within the run element, the
      start and end time must be specified, and the integration timestep size
      (the inverse of the integration frequency). Note that the start time will
      almost always be 0.0, and so the end time merely specifies the duration of
      the run.
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
        <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation><xs:documentation>
            A property element placed within the run element (in a sort of
            "global" script space) allows variables to be created for scripting.
            The property can be given an initial value, as well.
          </xs:documentation></xs:annotation>
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="property-with-value">
                <xs:attribute name="persistent" type="xs:boolean"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element ref="event" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="start" type="xs:decimal" use="optional">
        <xs:annotation><xs:documentation>
          This attribute is not currently used. A script will always begin
          execution at time 0.0.
        </xs:documentation></xs:annotation>
      </xs:attribute>
      <xs:attribute name="end" type="xs:decimal" use="required">
        <xs:annotation><xs:documentation>
          Since script execution always begins at time 0.0, the "end" attribute
          is essentially the same thing as the duration of the script.
        </xs:documentation></xs:annotation>
      </xs:attribute>
      <xs:attribute name="dt" type="xs:decimal" use="required">
        <xs:annotation><xs:documentation>
          The dt attribute is simply the frame time, or the times step size.
        </xs:documentation></xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="event">
    <xs:annotation><xs:documentation>
      The "event" element (if any) has as its parent the "run" element. There
      may be any number of event elements defined - even none at all. An event
      element may feature a name attribute, and/or a persistent attribute.
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="condition" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="set" maxOccurs="unbounded" minOccurs="0"/>
          <xs:element ref="notify" minOccurs="1" maxOccurs="1"/>
          <xs:element name="delay" type="xs:decimal" minOccurs="0" maxOccurs="1">
            <xs:annotation><xs:documentation>
              The delay element represents the number of seconds to delay in
              executing the set actions for an event once the conditions have
              been met.
            </xs:documentation></xs:annotation>
          </xs:element>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="name" type="xs:token" use="optional"/>
      <xs:attribute name="persistent" type="xs:boolean" use="optional" default="false">
        <xs:annotation><xs:documentation>
          If an event is marked persistent, the event will be executed anytime
          the condition[s] first evaluate to true after toggling from false.
          Otherwise, the event only executes the first time the condition
          evaluates toggles to true.
        </xs:documentation></xs:annotation>
      </xs:attribute>
      <xs:attribute name="continuous" type="xs:boolean" use="optional" default="false">
        <xs:annotation><xs:documentation>
          If an event is marked as "continuous", the "set" action will be
          executed at all times while the conditions evaluate to true. This is
          not only relevant when a property is set via the exponential approach
          method. If a function is used within the "set" element to define the
          value that the event will assign, the use of the continuous attribute
          (set to true) causes the function to be evaluated continuously while
          the condition evaluates to true.
        </xs:documentation></xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="condition">
    <xs:annotation><xs:documentation>
      The condition element has as its parent the "event" element. The condition
      element specifies the test or tests that must evaluate to true if the
      event is to have its "set" actions carried out. Conditions are specified
      in the form:
        {property} {operation} {property|number}
      where {property} is simply a property name, and {operation} is one of the
      comparison operators (gt, ge, lt, le, eq, ne) in lower or upper case. For
      example:
        sim-time-sec ge 5.0
      Any number of conditional tests such as the one above may be listed.
      Additionally, further groupings of conditional tests may be collected
      within a test element.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="test" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="logic" type="AND-OR" default="AND"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="notify">
    <xs:annotation><xs:documentation>
      The "notify" element may appear by itself, or it may group together
      properties. The notify element specifies that the program should print out
      a notification message when the event is executed (when its conditions
      evaluate to true). If the notify element contains properties, the values
      of those properties will also be printed when the event is triggered.
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
        <xs:element name="property" type="property-with-caption"/>
      </xs:sequence>
      <xs:attribute name="format" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="kml"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="set">
    <xs:annotation><xs:documentation>
      The "set" element is the mechanism by which the JSBSim Scripting function
      carries out actions, setting the value of a property or properties to the
      specified value, or change in value, when the event conditions have been
      met. Once a condition has been met, a value may be assigned to a property
      directory via a step change, via an exponential approach, or via a ramp
      (when supplied with the time constant for the latter two).
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:all minOccurs="0">
        <xs:element minOccurs="0" ref="function"/>
      </xs:all>
      <xs:attribute name="name" type="xs:token" use="required"/>
      <xs:attribute name="action" use="optional" default="FG_STEP">
        <xs:annotation><xs:documentation>
          The action specifies how the new value should be reached from the old
          value. The choices are: step, ramp, exponential approach.
        </xs:documentation></xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="FG_RAMP"/>
            <xs:enumeration value="FG_STEP"/>
            <xs:enumeration value="FG_EXP"/>
            <xs:enumeration value="ramp"/>
            <xs:enumeration value="step"/>
            <xs:enumeration value="exp"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="value" type="xs:double" use="optional"/>
      <xs:attribute name="tc" type="xs:double" use="optional"/>
      <xs:attribute name="type" use="optional" default="FG_VALUE">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="FG_DELTA"/>
            <xs:enumeration value="FG_VALUE"/>
            <xs:enumeration value="FG_BOOL"/>
            <xs:enumeration value="delta"/>
            <xs:enumeration value="value"/>
            <xs:enumeration value="bool"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="test">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="test"/>
      </xs:sequence>
      <xs:attribute name="logic" type="AND-OR" default="AND"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="independentVar" />
        <xs:element ref="tableData" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" use="optional" type="xs:token" />
    </xs:complexType>
  </xs:element>
  <xs:element name="independentVar">
    <xs:complexType mixed="true">
      <xs:attribute name="lookup" type="xs:token" />
    </xs:complexType>
  </xs:element>
  <xs:element name="tableData">
    <xs:simpleType>
      <xs:list itemType="xs:decimal"/>
    </xs:simpleType>
    <!-- <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="breakPoint" type="xs:double" use="optional" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType> -->
  </xs:element>

</xs:schema>

=== JSBSim-Team/jsbsim/scripts/weather-balloon.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<!-- JSBSim -aircraft=weather-balloon -initfile=reset10 -logdirectivefile=aircraft/weather-balloon/balloon_log.xml -end-time=600000 -simulation-rate=120 -->
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="Launch the weather balloon">
  <description>This run is for testing the weather balloon model.</description>
  <use aircraft="weather-balloon" initialize="reset10"/>
  <run start="0.0" end="600000" dt="0.00833333">
    <property value="60"> simulation/notify-time-trigger </property>
    <event name="initialize">
      <condition>simulation/sim-time-sec  ge  0.25</condition>
      <notify/>
    </event>

    <event name="Repeating Notify" persistent="true">
      <description>Output message at periodic intervals</description>
      <notify>
        <property>position/h-agl-ft</property>
        <property>velocities/vt-fps</property>
        <property>metrics/radius-ft</property>
      </notify>
      <condition> simulation/sim-time-sec >= simulation/notify-time-trigger </condition>
      <set name="simulation/notify-time-trigger" value="60" type="FG_DELTA"/>
    </event>

    <event name="Burst">
      <description>Log the burst event.</description>
      <notify>
        <property>position/h-agl-ft</property>
        <property>velocities/vt-fps</property>
        <property>metrics/radius-ft</property>
      </notify>
      <set name="buoyant_forces/gas-cell/contents-mol" value="0.001"/>
      <condition> buoyant_forces/gas-cell/burst ge 0.5 </condition>
    </event>

    <event name="Terminate">
      <description> End condition. Balloon is empty and on the ground. </description>
      <condition>
           metrics/radius-ft lt 0.1
           position/h-agl-ft lt 1
      </condition>
      <set name="simulation/terminate" value="1.0"/>
      <notify>
        <property>simulation/sim-time-sec</property>
      </notify>
    </event>
  </run>
</runscript>

=== JSBSim-Team/jsbsim/scripts/c172_cross_wind.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="C172-01A">
  <use aircraft="c172x" initialize="reset00"/>
  <run start="0.0" end="25" dt="0.008333">
    <!--
        This test demonstrates pitch oscillations of high amplitude of the c172
        due to a moderate cross wind (5kts beta=90 deg) as reported in issue
        #89.
        The vertical component of the cross wind is key to the triggering of the
        oscillations.
    -->

    <!-- Initialize with brakes on -->
    <property value="1"> fcs/left-brake-cmd-norm </property>
    <property value="1"> fcs/right-brake-cmd-norm </property>

    <event name="Trim on ground">
      <condition>simulation/sim-time-sec ge 0.1 </condition>
      <set name="simulation/do_simple_trim" value="2" />
    </event>

    <event name="wind speed buildup">
      <condition>simulation/sim-time-sec  ge  1.0</condition>
      <set name="atmosphere/wind-east-fps" action="FG_RAMP" value="-5.0" tc="10.0"/>
      <set name="atmosphere/wind-down-fps" action="FG_RAMP" value="-0.1" tc="10.0"/>
    </event>
  </run>
  <output name="cross_wind.csv" type="CSV" rate="120">
    <rates>            ON </rates>
    <velocities>       ON </velocities>
    <position>         ON </position>
    <atmosphere>       ON </atmosphere>
    <fcs>              ON </fcs>
    <ground_reactions> ON </ground_reactions>
    <propulsion>       ON </propulsion>
    <simulation>       ON </simulation>
    <massprops>        ON </massprops>
    <forces>           ON </forces>
    <moments>          ON </moments>
    <aerosurfaces>     ON </aerosurfaces>
    <coefficients>     ON </coefficients>
    <property> aero/alpha-rad         </property>
    <property> aero/alphadot-rad_sec  </property>
  </output>
</runscript>

=== JSBSim-Team/jsbsim/scripts/c172_cruise_8K.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sourceforge.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="C172 cruise at 4K, 100% power">
  <description>This run is for testing the C172 altitude hold autopilot and cruise performance</description>
  <use aircraft="c172x" initialize="reset01"/>

  <run start="0.0" end="50" dt="0.0083333">
  
    <property value="0" persistent="true"> simulation/run_id </property>

    <event name="Set Temperature">
      <condition>
        simulation/sim-time-sec  ge  0.0
      </condition>
      <set name="atmosphere/delta-T">
        <function>
          <switch>
            <p> simulation/run_id </p>
            <v>   0.0 </v>
            <v> -36.0 </v>
            <v>  36.0 </v>
          </switch>
        </function>
      </set>
      <set name="ap/altitude_setpoint" value="4000.0"/>
    </event>
    
    <event name="Start engine">
      <condition>
        simulation/sim-time-sec  ge  0.01
      </condition>
      <set name="fcs/throttle-cmd-norm" action="FG_RAMP" value="0.50" tc="0.05"/>
      <set name="fcs/mixture-cmd-norm" action="FG_RAMP" value="1.0" tc="0.05"/> 
      <set name="propulsion/magneto_cmd" value="3"/>
      <set name="propulsion/starter_cmd" value="1"/>
      <notify/>
    </event> 

    <event name="Trim">
      <condition>
        simulation/sim-time-sec  gt  1.0
      </condition>
      <set name="simulation/do_simple_trim" value="1"/>
      <notify>
        <property> velocities/u-aero-fps </property>
        <property> velocities/v-aero-fps </property>
        <property> velocities/w-aero-fps </property>
        <property> attitude/psi-rad </property>
        <property> attitude/theta-rad </property>
        <property> attitude/phi-rad </property>
        <property> position/h-agl-ft </property>
        <property> accelerations/pdot-rad_sec2 </property>
        <property> accelerations/qdot-rad_sec2 </property>
        <property> accelerations/rdot-rad_sec2 </property>
        <property> propulsion/engine/thrust-lbs </property>
        <property> propulsion/engine/propeller-rpm </property>
        <property> velocities/p-rad_sec </property>
        <property> velocities/q-rad_sec </property>
        <property> velocities/r-rad_sec </property>
        <property> fcs/elevator-cmd-norm </property>
        <property> fcs/aileron-cmd-norm </property>
        <property> fcs/rudder-cmd-norm </property>
        <property> fcs/elevator-pos-norm </property>
        <property> fcs/right-aileron-pos-norm </property>
        <property> fcs/rudder-pos-norm </property>
        <property> fcs/throttle-pos-norm[0] </property>
        <property> fcs/mixture-pos-norm[0] </property>
        <property> inertia/weight-lbs </property>
        <property> velocities/vc-kts </property>
        <property> velocities/ve-kts </property>
        <property> velocities/vtrue-kts </property>
        <property> atmosphere/T-R </property>
        <property> propulsion/engine/fuel-flow-rate-gph </property>
        <property> propulsion/engine/power-hp </property>
      </notify>
    </event>

    <event name="Hold heading and altitude">
      <condition>simulation/sim-time-sec ge 5</condition>
      <set name="ap/heading_setpoint" value="200"/>
      <set name="ap/heading_hold" value="1"/>
      <set name="ap/altitude_setpoint" value="4000.0"/>
      <set name="ap/altitude_hold" value="1"/>
      <notify/>
    </event>

    <event name="Introduce gust">
      <condition> simulation/sim-time-sec ge 10 </condition>
      <set name="atmosphere/cosine-gust/startup-duration-sec" value="5"/>
      <set name="atmosphere/cosine-gust/steady-duration-sec" value="1"/>
      <set name="atmosphere/cosine-gust/end-duration-sec" value="5"/>
      <set name="atmosphere/cosine-gust/magnitude-ft_sec" value="30"/>
      <set name="atmosphere/cosine-gust/frame" value="2"/>
      <set name="atmosphere/cosine-gust/X-velocity-ft_sec" value="-1"/>
      <set name="atmosphere/cosine-gust/Y-velocity-ft_sec" value="0"/>
      <set name="atmosphere/cosine-gust/Z-velocity-ft_sec" value="0"/>
      <set name="atmosphere/cosine-gust/start" value="1"/>
      <notify/>
    </event>

    <event name="Reset">
      <condition logic="AND">
        simulation/sim-time-sec >= 30.0
        simulation/terminate != 1
      </condition>
      <set name="ap/heading_setpoint" value="0"/>
<!--      <set name="ap/altitude_setpoint" value="0"/> -->
      <set name="ap/altitude_hold" value="0"/>
      <set name="ap/heading_hold" value="0"/>
      <set name="simulation/reset" value="1"/>
      <set name="simulation/run_id" type="FG_DELTA" value="1"/>
      <notify>
        <property> simulation/run_id </property>
      </notify>
    </event>

    <event name="Terminate on run ID">
      <condition>
        simulation/run_id  ge  3
      </condition>
      <set name="simulation/terminate" value="1"/>
      <notify>
        <property caption="Terminate: "> simulation/terminate </property>
      </notify>
    </event>

  </run>
</runscript>

=== JSBSim-Team/jsbsim/cessna_crosswind_simulation.xml
<?xml version="1.0" encoding="UTF-8"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://jsbsim.sourceforge.net/JSBSimScript.xsd"
           name="Cessna 172 Crosswind Landing">
           
  <description>
    Cessna 172 crosswind landing simulation
    Wind: 15.0 kts from 90.0 degrees
    Approach: -3.0 degree glideslope
  </description>

  <use aircraft="c172p" initialize="cruise"/>

  <!-- 초기 조건 설정 -->
  <run start="0.0" end="120.0" dt="0.01">
    
    <!-- 초기 위치 및 자세 -->
    <property value="0.0">ic/lat-gc-deg</property>
    <property value="0.0">ic/long-gc-deg</property>
    <property value="500.0">ic/h-sl-ft</property>
    <property value="70.0">ic/vc-kts</property>
    <property value="0.0">ic/gamma-deg</property>
    <property value="90.0">ic/psi-true-deg</property>
    
    <!-- 횡풍 조건 설정 -->
    <property value="15.0">atmosphere/wind-mag-fps</property>
    <property value="90.0">atmosphere/wind-dir-deg</property>
    <property value="0.0">atmosphere/wind-down-fps</property>
    
    <!-- 자동조종장치 해제 (수동 조종) -->
    <property value="0">ap/autopilot_engage</property>
    
    <!-- 엔진 설정 (접근 파워) -->
    <property value="0.4">fcs/throttle-cmd-norm</property>
    <property value="0.4">fcs/mixture-cmd-norm</property>
    
    <!-- 착륙장치 전개 -->
    <property value="1">gear/gear-cmd-norm</property>
    
    <!-- 플랩 설정 (착륙 설정) -->
    <property value="30">fcs/flap-cmd-deg</property>
    
    <!-- 횡풍 접근 이벤트들 -->
    
    <!-- 0-30초: 안정화된 접근 -->
    <event name="stable_approach" persistent="false">
      <condition>simulation/sim-time-sec ge 0.0</condition>
      <set name="fcs/elevator-cmd-norm" value="-0.1"/>
      <set name="fcs/aileron-cmd-norm" value="0.0"/>
      <set name="fcs/rudder-cmd-norm" value="0.0"/>
    </event>
    
    <!-- 30-60초: 횡풍 보정 시작 (크랩 방법) -->
    <event name="crab_correction" persistent="false">
      <condition>simulation/sim-time-sec ge 30.0</condition>
      <set name="fcs/rudder-cmd-norm" value="0.2"/>  <!-- 풍향으로 기수 돌림 -->
      <notify>
        <property>simulation/sim-time-sec</property>
        <property>aero/beta-deg</property>
        <property>attitude/psi-deg</property>
      </notify>
    </event>
    
    <!-- 60-90초: 사이드슬립 전환 -->
    <event name="sideslip_transition" persistent="false">
      <condition>simulation/sim-time-sec ge 60.0</condition>
      <set name="fcs/aileron-cmd-norm" value="-0.15"/>  <!-- 풍상측 에일러론 -->
      <set name="fcs/rudder-cmd-norm" value="0.1"/>     <!-- 반대 러더로 균형 -->
      <notify>
        <property>simulation/sim-time-sec</property>
        <property>aero/beta-deg</property>
        <property>attitude/phi-deg</property>
      </notify>
    </event>
    
    <!-- 90-120초: 최종 접지 접근 -->
    <event name="final_approach" persistent="false">
      <condition>simulation/sim-time-sec ge 90.0</condition>
      <set name="fcs/aileron-cmd-norm" value="-0.2"/>
      <set name="fcs/rudder-cmd-norm" value="0.15"/>
      <set name="fcs/elevator-cmd-norm" value="0.05"/>  <!-- 플레어 시작 -->
      <notify>
        <property>simulation/sim-time-sec</property>
        <property>position/h-agl-ft</property>
        <property>aero/beta-deg</property>
      </notify>
    </event>

    <!-- 데이터 로깅 설정 -->
    <event name="log_data" persistent="true">
      <condition>simulation/sim-time-sec ge 0.0</condition>
      <notify format="CSV">
        <property caption="Time">simulation/sim-time-sec</property>
        <property caption="Altitude_AGL">position/h-agl-ft</property>
        <property caption="Airspeed">velocities/vc-kts</property>
        <property caption="Sideslip">aero/beta-deg</property>
        <property caption="Heading">attitude/psi-deg</property>
        <property caption="Roll">attitude/phi-deg</property>
        <property caption="Pitch">attitude/theta-deg</property>
        <property caption="Lateral_Pos">position/distance-from-start-lon-mt</property>
        <property caption="Side_Force">forces/fby-lbs</property>
        <property caption="Yaw_Moment">moments/n-aero-lbsft</property>
        <property caption="Roll_Moment">moments/l-aero-lbsft</property>
        <property caption="Wind_Speed">atmosphere/wind-mag-fps</property>
        <property caption="Wind_Dir">atmosphere/wind-dir-deg</property>
        <property caption="Aileron">fcs/aileron-pos-norm</property>
        <property caption="Rudder">fcs/rudder-pos-norm</property>
        <property caption="Elevator">fcs/elevator-pos-norm</property>
      </notify>
    </event>
    
  </run>

</runscript>
