=== JSBSim-Team/jsbsim/JSBSimScript.xsd
<?xml version="1.0"?>
<!--<?xml-stylesheet type="text/xsl" href="XMLToDoc.xsl"?>-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation><xs:documentation>
    This schema specifies the format that a JSBSim (www.jsbsim.org) script must
    take to be valid. The JSBSim scripting language provides for specification
    of which aircraft and initialization file will be used for a "batch" run, as
    well as how long it will run, and at what time-step size it will be
    integrated at. Also, "Events" may be defined that can direct the simulation
    to set parameter values when specific conditions have been reached. The
    script author may also specify that some notifications should take place
    when an event is reached.
  </xs:documentation></xs:annotation>

  <xs:include schemaLocation="JSBSimCommon.xsd"/>

  <xs:element name="runscript">
    <xs:annotation><xs:documentation>
      The "runscript" element is the top-level containing XML element. It may
      have a name attribute, that describes briefly what the script does.
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
        <xs:element name="use" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="aircraft" type="xs:token" use="required"/>
            <xs:attribute name="initialize" type="xs:token" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element ref="run" maxOccurs="1"/>
        <xs:element name="output" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="rates" type="ON-OFF" minOccurs="0"/>
              <xs:element name="velocities" type="ON-OFF" minOccurs="0"/>
              <xs:element name="position" type="ON-OFF" minOccurs="0"/>
              <xs:element name="atmosphere" type="ON-OFF" minOccurs="0"/>
              <xs:element name="fcs" type="ON-OFF" minOccurs="0"/>
              <xs:element name="ground_reactions" type="ON-OFF" minOccurs="0"/>
              <xs:element name="propulsion" type="ON-OFF" minOccurs="0"/>
              <xs:element name="simulation" type="ON-OFF" minOccurs="0"/>
              <xs:element name="massprops" type="ON-OFF" minOccurs="0"/>
              <xs:element name="forces" type="ON-OFF" minOccurs="0"/>
              <xs:element name="moments" type="ON-OFF" minOccurs="0"/>
              <xs:element name="aerosurfaces" type="ON-OFF" minOccurs="0"/>
              <xs:element name="coefficients" type="ON-OFF" minOccurs="0"/>
              <xs:element name="property" type="property-with-caption" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:token" use="required"/>
            <xs:attribute name="type" use="required">
              <xs:annotation><xs:documentation>
                The format in which the data output will be issued.
              </xs:documentation></xs:annotation>
              <xs:simpleType>
                <xs:restriction base="xs:token">
                  <xs:enumeration value="CSV"/>
                  <xs:enumeration value="TABULAR"/>
                  <xs:enumeration value="SOCKET"/>
                  <xs:enumeration value="FLIGHTGEAR"/>
                  <xs:enumeration value="TERMINAL"/>
                  <xs:enumeration value="NONE"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="rate" type="xs:decimal" use="required"/>
            <xs:attribute name="file" type="xs:token" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:token" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="property-with-caption">
    <xs:simpleContent>
      <xs:extension base="property">
        <xs:attribute name="caption" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:element name="run">
    <xs:annotation><xs:documentation>
      The "run" element has as its parent the "runscript" element. The run
      element contains any and all "event" elements. Within the run element, the
      start and end time must be specified, and the integration timestep size
      (the inverse of the integration frequency). Note that the start time will
      almost always be 0.0, and so the end time merely specifies the duration of
      the run.
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
        <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation><xs:documentation>
            A property element placed within the run element (in a sort of
            "global" script space) allows variables to be created for scripting.
            The property can be given an initial value, as well.
          </xs:documentation></xs:annotation>
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="property-with-value">
                <xs:attribute name="persistent" type="xs:boolean"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element ref="event" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="start" type="xs:decimal" use="optional">
        <xs:annotation><xs:documentation>
          This attribute is not currently used. A script will always begin
          execution at time 0.0.
        </xs:documentation></xs:annotation>
      </xs:attribute>
      <xs:attribute name="end" type="xs:decimal" use="required">
        <xs:annotation><xs:documentation>
          Since script execution always begins at time 0.0, the "end" attribute
          is essentially the same thing as the duration of the script.
        </xs:documentation></xs:annotation>
      </xs:attribute>
      <xs:attribute name="dt" type="xs:decimal" use="required">
        <xs:annotation><xs:documentation>
          The dt attribute is simply the frame time, or the times step size.
        </xs:documentation></xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="event">
    <xs:annotation><xs:documentation>
      The "event" element (if any) has as its parent the "run" element. There
      may be any number of event elements defined - even none at all. An event
      element may feature a name attribute, and/or a persistent attribute.
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="condition" minOccurs="0" maxOccurs="1"/>
          <xs:element ref="set" maxOccurs="unbounded" minOccurs="0"/>
          <xs:element ref="notify" minOccurs="1" maxOccurs="1"/>
          <xs:element name="delay" type="xs:decimal" minOccurs="0" maxOccurs="1">
            <xs:annotation><xs:documentation>
              The delay element represents the number of seconds to delay in
              executing the set actions for an event once the conditions have
              been met.
            </xs:documentation></xs:annotation>
          </xs:element>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="name" type="xs:token" use="optional"/>
      <xs:attribute name="persistent" type="xs:boolean" use="optional" default="false">
        <xs:annotation><xs:documentation>
          If an event is marked persistent, the event will be executed anytime
          the condition[s] first evaluate to true after toggling from false.
          Otherwise, the event only executes the first time the condition
          evaluates toggles to true.
        </xs:documentation></xs:annotation>
      </xs:attribute>
      <xs:attribute name="continuous" type="xs:boolean" use="optional" default="false">
        <xs:annotation><xs:documentation>
          If an event is marked as "continuous", the "set" action will be
          executed at all times while the conditions evaluate to true. This is
          not only relevant when a property is set via the exponential approach
          method. If a function is used within the "set" element to define the
          value that the event will assign, the use of the continuous attribute
          (set to true) causes the function to be evaluated continuously while
          the condition evaluates to true.
        </xs:documentation></xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="condition">
    <xs:annotation><xs:documentation>
      The condition element has as its parent the "event" element. The condition
      element specifies the test or tests that must evaluate to true if the
      event is to have its "set" actions carried out. Conditions are specified
      in the form:
        {property} {operation} {property|number}
      where {property} is simply a property name, and {operation} is one of the
      comparison operators (gt, ge, lt, le, eq, ne) in lower or upper case. For
      example:
        sim-time-sec ge 5.0
      Any number of conditional tests such as the one above may be listed.
      Additionally, further groupings of conditional tests may be collected
      within a test element.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="test" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="logic" type="AND-OR" default="AND"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="notify">
    <xs:annotation><xs:documentation>
      The "notify" element may appear by itself, or it may group together
      properties. The notify element specifies that the program should print out
      a notification message when the event is executed (when its conditions
      evaluate to true). If the notify element contains properties, the values
      of those properties will also be printed when the event is triggered.
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="description" minOccurs="0" maxOccurs="1" type="xs:string"/>
        <xs:element name="property" type="property-with-caption"/>
      </xs:sequence>
      <xs:attribute name="format" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="kml"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="set">
    <xs:annotation><xs:documentation>
      The "set" element is the mechanism by which the JSBSim Scripting function
      carries out actions, setting the value of a property or properties to the
      specified value, or change in value, when the event conditions have been
      met. Once a condition has been met, a value may be assigned to a property
      directory via a step change, via an exponential approach, or via a ramp
      (when supplied with the time constant for the latter two).
    </xs:documentation></xs:annotation>
    <xs:complexType>
      <xs:all minOccurs="0">
        <xs:element minOccurs="0" ref="function"/>
      </xs:all>
      <xs:attribute name="name" type="xs:token" use="required"/>
      <xs:attribute name="action" use="optional" default="FG_STEP">
        <xs:annotation><xs:documentation>
          The action specifies how the new value should be reached from the old
          value. The choices are: step, ramp, exponential approach.
        </xs:documentation></xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="FG_RAMP"/>
            <xs:enumeration value="FG_STEP"/>
            <xs:enumeration value="FG_EXP"/>
            <xs:enumeration value="ramp"/>
            <xs:enumeration value="step"/>
            <xs:enumeration value="exp"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="value" type="xs:double" use="optional"/>
      <xs:attribute name="tc" type="xs:double" use="optional"/>
      <xs:attribute name="type" use="optional" default="FG_VALUE">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="FG_DELTA"/>
            <xs:enumeration value="FG_VALUE"/>
            <xs:enumeration value="FG_BOOL"/>
            <xs:enumeration value="delta"/>
            <xs:enumeration value="value"/>
            <xs:enumeration value="bool"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="test">
    <xs:complexType mixed="true">
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="test"/>
      </xs:sequence>
      <xs:attribute name="logic" type="AND-OR" default="AND"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="independentVar" />
        <xs:element ref="tableData" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" use="optional" type="xs:token" />
    </xs:complexType>
  </xs:element>
  <xs:element name="independentVar">
    <xs:complexType mixed="true">
      <xs:attribute name="lookup" type="xs:token" />
    </xs:complexType>
  </xs:element>
  <xs:element name="tableData">
    <xs:simpleType>
      <xs:list itemType="xs:decimal"/>
    </xs:simpleType>
    <!-- <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="breakPoint" type="xs:double" use="optional" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType> -->
  </xs:element>

</xs:schema>

=== JSBSim-Team/jsbsim/scripts/c1722.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="At-altitude autopilot test setup.">
    
  <use aircraft="c172x" initialize="reset01"/>
  <run start="0.0" end="200" dt="0.00833333">
    <property value="19.65"> propulsion/tank[0]/unusable-volume-gal </property>
    <property value="19.65"> propulsion/tank[1]/unusable-volume-gal </property>
    
    <event name="Engine start">
      <condition>simulation/sim-time-sec  ge  0.25</condition>
      <set name="fcs/throttle-cmd-norm" value="0.65"/>
      <set name="fcs/mixture-cmd-norm" value="0.87"/>
      <set name="propulsion/magneto_cmd" value="3"/>
      <set name="propulsion/starter_cmd" value="1"/>
      <set name="ap/heading_hold" value="0"/>
      <notify>
        <property>velocities/vc-kts</property>
        <property>position/h-agl-ft</property>
        <property>propulsion/tank[0]/contents-lbs</property>
        <property>propulsion/tank[1]/contents-lbs</property>
        <property>propulsion/engine/set-running</property>
        <property>propulsion/engine/fuel-flow-rate-gph</property>
        <property>propulsion/engine/engine-rpm</property>
        <property>propulsion/engine/power-hp</property>
      </notify>
    </event>

    <event name="Engine starved">
      <condition>
        simulation/sim-time-sec gt 0.0
        propulsion/engine/set-running == 0.0
      </condition>
      <notify>
        <property>propulsion/tank[0]/contents-lbs</property>
        <property>propulsion/tank[1]/contents-lbs</property>
        <property>propulsion/engine/set-running</property>
        <property>propulsion/engine/fuel-flow-rate-gph</property>
        <property>propulsion/engine/engine-rpm</property>
        <property>propulsion/engine/power-hp</property>
      </notify>
    </event>
    
    <event name="Trim">
      <condition>simulation/sim-time-sec  ge  0.50</condition>
      <set name="simulation/do_simple_trim" value="0"/>
      <notify>
        <property>velocities/vc-kts</property>
        <property>position/h-agl-ft</property>
        <property>propulsion/tank[0]/contents-lbs</property>
        <property>propulsion/tank[1]/contents-lbs</property>
        <property>propulsion/engine/set-running</property>
        <property>propulsion/engine/fuel-flow-rate-gph</property>
        <property>propulsion/engine/engine-rpm</property>
        <property>propulsion/engine/power-hp</property>
      </notify>
    </event>

    <event name="Set roll autopilot">
      <condition>simulation/sim-time-sec  ge  5.0</condition>
      <set name="ap/attitude_hold" value="1"/>
      <notify>
        <property>velocities/vc-kts</property>
        <property>position/h-agl-ft</property>
        <property>propulsion/tank[0]/contents-lbs</property>
        <property>propulsion/tank[1]/contents-lbs</property>
        <property>propulsion/engine/fuel-flow-rate-gph</property>
        <property>propulsion/engine/engine-rpm</property>
        <property>propulsion/engine/power-hp</property>
      </notify>
    </event>

  </run>
</runscript>

=== JSBSim-Team/jsbsim/scripts/rudder_kick.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="Rudder kick test">

	<description>
		This script trims the aircraft and then inputs a rudder input 'kick' and aileron input.
		And equivalent JSBSim python based script can be found in examples\python\RudderKick.py
	</description>

	<use aircraft="737" initialize="rudder_kick_init"/>

	<run start="0" end="20" dt="0.008333">

		<property value="0"> simulation/notify-time-trigger </property>

		<!--
		For "do_simple_trim" (Classic trim):
		0: Longitudinal
		1: Full
		2: Ground
		3: Pullup
		4: Custom
		5: Turn
		6: None
		-->

		<event name="Start Trim">
			<condition> simulation/sim-time-sec ge 0 </condition>
			<set name="simulation/do_simple_trim" value="1"/>
		</event>

		<event name="RudderInput">
			<condition> simulation/sim-time-sec ge 0.1 </condition>
			<set name="fcs/rudder-cmd-norm" value="0.92" action="FG_RAMP" tc="3.0"></set>
			<notify />
		</event>

		<event name="AileronInput">
			<condition> simulation/sim-time-sec ge 0.1 </condition>
			<set name="fcs/aileron-cmd-norm" value="1.0" action="FG_RAMP" tc="3.0"></set>
			<notify />
		</event>

		<event name="Repeating Notify" persistent="true">
			<description>
				Output message at 1 second intervals, starting after
				trimming is completed.
			</description>
			<notify>
				<property>position/h-sl-ft</property>
				<property>velocities/vc-kts</property>
				<property>attitude/theta-deg</property>
				<property>aero/alpha-deg</property>
				<property>aero/beta-deg</property>
				<property>fcs/rudder-cmd-norm</property>
				<property>fcs/aileron-cmd-norm</property>
			</notify>
			<condition> simulation/sim-time-sec >= simulation/notify-time-trigger </condition>
			<set name="simulation/notify-time-trigger" value="1" type="FG_DELTA"/>
		</event>

	</run>

</runscript>

=== JSBSim-Team/jsbsim/scripts/c172_elevator_doublet.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sourceforge.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="C172 elevator doublet">
  <!--
    This run is for testing the C172 at altitude with an elevator doublet applied
  -->

  <use aircraft="c172x" initialize="elevator_doublet_init"/>
  <run start="0.0" end="40" dt="0.0083333">

    <property> simulation/notify-time-trigger </property>
    <property value="1"> simulation/run_id </property>

<!--
      For "do_simple_trim" (Classic trim):
      0: Longitudinal
      1: Full
      2: Ground
      3: Pullup
      4: Custom
      5: Turn
      6: None
-->
    <event name="Trim">
      <description>Trim at the initial conditions state</description>
      <condition>
        simulation/sim-time-sec gt 1.0
      </condition>
      <set name="simulation/do_simple_trim" value="1"/>
      <notify>
        <property>velocities/vc-kts</property>
        <property>velocities/vt-fps</property>
        <property>attitude/phi-rad</property>
        <property>attitude/theta-rad</property>
        <property>attitude/psi-rad</property>
      </notify>
    </event>

    <event name="Elevator doublet" continuous="true">
      <description> Do an elevator doublet from between
                    5 and 7 seconds. </description>
      <condition>
        simulation/sim-time-sec ge 5
        simulation/sim-time-sec le 7
      </condition>
      <set name="fcs/elevator-cmd-norm">
        <function>
          <sin>
            <product>
              <difference>
                <property> simulation/sim-time-sec </property>
                <value> 5 </value>
              </difference>
              <value> 3.1415927 </value>
            </product>
          </sin>
        </function>
      </set>
      <notify>
        <property>velocities/vc-kts</property>
        <property>velocities/vt-fps</property>
        <property>attitude/phi-rad</property>
        <property>attitude/theta-rad</property>
        <property>attitude/psi-rad</property>
      </notify>
    </event>

    <event name="Re-Trim at 20 seconds">
      <description>Trim at the initial conditions state</description>
      <condition>
        simulation/sim-time-sec gt 20.0
      </condition>
      <set name="simulation/do_simple_trim" value="1"/>
      <notify>
        <property>velocities/vc-kts</property>
        <property>velocities/vt-fps</property>
        <property>attitude/phi-rad</property>
        <property>attitude/theta-rad</property>
        <property>attitude/psi-rad</property>
      </notify>
    </event>

    <event name="Aileron doublet" continuous="true">
      <description>
        Do an elevator doublet from between
        25 and 27 seconds.
      </description>
      <condition>
        simulation/sim-time-sec ge 25
        simulation/sim-time-sec le 27
      </condition>
      <set name="fcs/aileron-cmd-norm">
        <function>
          <sin>
            <product>
              <difference>
                <property> simulation/sim-time-sec </property>
                <value> 25 </value>
              </difference>
              <value> 3.1415927 </value>
            </product>
          </sin>
        </function>
      </set>
      <notify>
        <property>velocities/vc-kts</property>
        <property>velocities/vt-fps</property>
        <property>attitude/phi-rad</property>
        <property>attitude/theta-rad</property>
        <property>attitude/psi-rad</property>
      </notify>
    </event>

  </run>
</runscript>

=== JSBSim-Team/jsbsim/aircraft/global5000/scripts/trim-cruise.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="Trim in Cruise configuration">

  <description>
    Trimmed at altitude/airspeed in Cruise configuration, 
    run for 1 second

      Author:
    Bill Galbraith
    Holy Cows, Inc.
    billg@holycows.net
    December 2010
    
      Modified by:
    Guilherme Lima da Silva
    ATS aerothermalsolutions.co 
    aerospace@ats4i.com 
    May 2021
    
  </description>          

  <use aircraft="global5000" initialize="airborne"/>

  <run start="0" end="2" dt="0.00833333">
  
      <property value="0"> simulation/notify-time-trigger </property>

    <!-- 
	  Specify the initial conditions for the test if
	  different than in the initialize script, and
	  trim the aircraft.
	-->
    <event name="Trim">
      <condition> simulation/sim-time-sec ge 0.0 </condition>
	  <set name="ic/vc-kts"  value="161.25"/>
	  <set name="ic/h-sl-ft" value="30000.0"/>
      <set name="simulation/do_simple_trim" value="1"/>
    </event>
 
      <event name="Repeating Notify" persistent="true">
      <description>Output message at 1 second interval, starting after
                   trimming is completed.
      </description>
      <notify>
        <property>position/h-agl-ft</property>
        <property>velocities/mach</property>  
        <property>propulsion/engine[0]/n2</property>
        <property>propulsion/engine[1]/n2</property>
        <property>propulsion/engine[0]/thrust-lbs</property>
        <property>propulsion/engine[1]/thrust-lbs</property>
        <property>velocities/vc-kts</property>
<!--        <property>velocities/vc-fps</property>-->
<!--        <property>velocities/vt-fps</property>-->
<!--        <property>attitude/theta-rad</property>-->
        <property>aero/alpha-deg</property>
        <property>simulation/frame</property>
      </notify>
      <condition logic="AND">
        simulation/sim-time-sec >= simulation/notify-time-trigger
        simulation/trim-completed eq 1
      </condition>

      <set name="simulation/notify-time-trigger" value="1" type="FG_DELTA"/>
      <notify/>
      
    </event>

  </run>

</runscript>

=== JSBSim-Team/jsbsim/scripts/737_test.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="http://jsbsim.sf.net/JSBSimScript.xsl"?>
<runscript xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://jsbsim.sf.net/JSBSimScript.xsd"
    name="Cruise flight in 737.">

  <description>
    This script trims the aircraft at cruise altitude and mach. Some state
    data is printed out at the completion of trimming. 
  </description>

  <use aircraft="737" initialize="cruise_init"/> 

  <run start="0" end="1" dt="0.008333">

    <property value="0"> simulation/notify-time-trigger </property>

    <event name="Reset Initial Conditions"> 
      <condition> simulation/sim-time-sec ge 0 </condition>
      <set name="ic/h-sl-ft" value="30000"/>
      <set name="ic/mach"    value="0.78"/>
      <notify>
        <property caption="Altitude ASL">ic/h-sl-ft</property>
        <property caption="Mach .......">ic/mach</property>
      </notify>
    </event>

    <event name="Set engines running / raise gear">
      <condition> simulation/sim-time-sec ge 0 </condition>
      <set name="propulsion/engine[0]/set-running" value="1"/>
      <set name="propulsion/engine[1]/set-running" value="1"/>
      <set name="gear/gear-cmd-norm" value="0"/>
      <set name="gear/gear-pos-norm" value="0"/>
      <notify>
        <property caption="Eng[0] Thrust (lbs)">propulsion/engine[0]/thrust-lbs</property>
        <property caption="Eng[1] Thrust (lbs)">propulsion/engine[1]/thrust-lbs</property>
        <property caption="Gear Position .....">gear/gear-pos-norm</property>
      </notify>
    </event>

    <!--
      For "do_simple_trim" (Classic trim):
      0: Longitudinal
      1: Full
      2: Ground
      3: Pullup
      4: Custom
      5: Turn
      6: None
    -->
    
    <event name="Start Trim">
      <condition> gear/gear-pos-norm eq 0 </condition>
      <set name="simulation/do_simple_trim" value="0"/>
    </event>


    <event name="Repeating Notify" persistent="true">
      <description>Output message at 10 second intervals, starting after
                   trimming is completed.
      </description>
      <notify>
        <property>position/h-agl-ft</property>
        <property>velocities/mach</property>  
        <property>propulsion/engine[0]/n2</property>
        <property>propulsion/engine[1]/n2</property>
        <property>propulsion/engine[0]/thrust-lbs</property>
        <property>propulsion/engine[1]/thrust-lbs</property>
        <property>velocities/vc-kts</property>
        <property>velocities/vc-fps</property>
        <property>velocities/vt-fps</property>
        <property>attitude/theta-rad</property>
        <property>aero/alpha-deg</property>
        <property>simulation/frame</property>
      </notify>
      <condition logic="AND">
        simulation/sim-time-sec >= simulation/notify-time-trigger
        simulation/trim-completed eq 1
      </condition>
      <set name="simulation/notify-time-trigger" value="10" type="FG_DELTA"/>
    </event>

  </run>

</runscript>
